# Use the official SQLite image as the base image
FROM alpine

# Set the working directory inside the container
WORKDIR D:\Web\ToDoList

# Copy the database file to the container
COPY database.db .

# Expose any ports if needed (for example, if you're using a database that requires it)
# EXPOSE 5432

# No need for CMD, as this container will be used as a data container